Sinatraでメモアプリを作成
maimux2x/MemoApp pull request #1
Opened 2022-08-06 15:14 UTC by maimux2x

## やったこと
Sinatraを使ってメモの新規作成、閲覧、編集、削除を可能とした。

## rubocop
![rubocop](https://user-images.githubusercontent.com/76797372/183254835-56175f41-a77d-493c-9b14-be9ccce00dba.png)
## 各画面
![index](https://user-images.githubusercontent.com/76797372/183254851-d60c6e86-15a7-4aee-8b5c-b10407122043.png)

![new](https://user-images.githubusercontent.com/76797372/183254867-73b08aee-dfd7-4143-885e-81a1fefa57be.png)
![index2](https://user-images.githubusercontent.com/76797372/183254877-50a2ea37-af61-42c2-a821-ae3e3c89c16b.png)
![show](https://user-images.githubusercontent.com/76797372/183254880-58c2f022-2c5d-4442-8dc0-d7b4d07a83a3.png)
![show2](https://user-images.githubusercontent.com/76797372/183254886-753d374c-2ccc-401c-b6c1-5b75cf947294.png)
![edit](https://user-images.githubusercontent.com/76797372/183254900-ad56429f-5ca6-4829-923e-c999800b130c.png)

https://user-images.githubusercontent.com/76797372/183254938-9734eb1f-8e7f-4c77-a644-e182dd4c3213.mp4

![404](https://user-images.githubusercontent.com/76797372/183254948-3ca4103f-9865-4d24-b8eb-78334aa76cd1.png)

2022-08-09 08:40 UTC, func09 requested changes
とても良く書けていて読みやすいです！
新規作成のURLが REST にならったURLになっていませんでしたので
その点の修正をお願いします！

2022-08-09 08:40 UTC, func09 commented on views/index.erb
> +<% if @memos.length == 0 %>
👍

2022-08-09 08:40 UTC, func09 commented on memo_app.rb
> +    Rack::Utils.escape_html(text)
🆒

2022-08-09 08:40 UTC, func09 commented on memo_app.rb
> +  all_memos = get_memos('memos.json')
`memos.json` が何度も出てくるので定数に代入して再利用してあげると良いと思いました

2022-08-09 08:40 UTC, func09 commented on memo_app.rb
> +  @all_memos = all_memos
ここを２行に分ける必要はないので

```suggestion
  @all_memos = get_memos('memos.json')
```

これで良さそうです。

2022-08-09 08:40 UTC, func09 commented on memo_app.rb
> +post '/memos/new' do
RESTのプラクティスを思い出してください。
作成のURLは メソッドが POST なのは OKとして、 `new` は必要でしたか？

2022-08-09 14:37 UTC, maimux2x commented on memo_app.rb
> +  @all_memos = all_memos
こちら修正いたしました🙏

2022-08-09 14:38 UTC, maimux2x commented on memo_app.rb
> +post '/memos/new' do
修正しました🙇🏻
復習します！

2022-08-09 14:48 UTC, maimux2x commented on memo_app.rb
> +  all_memos = get_memos('memos.json')
ありがとうございます！
1点質問なのですが、今回私が書いたコードの場合、定数の定義はmainエリアで問題ないでしょうか？
本来はクラスの中で定義して `クラス名::定数名` で参照するのが正しいのかな？と思ったのですが、`BaseMemoData` クラスはメモのインスタンスを管理するためのものになるため、その中でファイル名を定数定義しない方が良いと考えました。
まだクラスの使い方や詳しい理解がいまいち追いついておらず、確認させていただけると幸いです。
（ピントがずれた質問だったら申し訳ありません...）

2022-08-10 06:44 UTC, func09 commented on memo_app.rb
> +post '/memos' do
💯

2022-08-10 06:44 UTC, func09 commented on memo_app.rb
> +  all_memos = get_memos('memos.json')
> 定数の定義はmainエリアで問題ないでしょうか？

確認しましたが定義している場所に問題はないですよ。

> 本来はクラスの中で定義して クラス名::定数名 で参照するのが正しいのかな？

定数をクラスの中に定義しなければいけないということはありませんね。

> BaseMemoData クラスはメモのインスタンスを管理するためのものになるため、その中でファイル名を定数定義しない方が良いと考えました。

細かい話になってしまいますが BaseMemoData の中に定数が指定されていたら、JSONファイルを入れ替えられる抽象度が下がってしまうので、BaseMemoDataの外側（メインの領域）に `FILE_NAME` を定義するのがベターだと思います！

2022-08-10 06:44 UTC, func09 approved these changes
LGTM!

2022-08-10 14:00 UTC, merged